export const mockCategories = [
  "Fantasia",
  "Jovem Adulto",
  "Ficção científica",
  "Ação e aventura",
  "Ficção histórica",
  "Horror",
  "Drama",
  "Comédia",
  "Distopia",
  "Biografia",
  "Romance",
  "Relato Real",
  "Literatura Erotica",
  "LGBTQ+",
  "Novela",
  "Ficção Policial",
  "Conto",
  "Ficção Contemporânea",
  "Thriller e Suspense",
  "Mistério",
  "Autoajuda",
  "Guias",
  "Adaptação",
  "Novo Adulto",
  "Realismo mágico",
  "Infantil",
  "Memórias",
  "Musicais",
  "Poema",
  "Poesia",
  "Autobiografia",
  "Fanfic",
  "Água com açúcar",
  "Religioso",
  "Familiar",
  "História",
  "Humor",
];
